### ISSUE TITLE
Whatsapp export is not working

### ISSUE THREAD

**Issue by sidpauhal** [ajith-ab/react-native-file-share-intent#8] opened 2019-09-18 13:37 UTC
Hi,
This lib is working and it shows in app list when I try to share photos, images or documents.

But this lib does not work when I try to export chat from whtsapp, other apps like message, email etc are showing but my app which I build is not showing in the list.
Please help I am trying to build a share extension for whatsapp

My package.json

"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-file-share-intent": "^1.1.2"
  },

**Comment by sidpauhal** [comment] 2019-09-27 07:34
@ajith-ab  Any update on this?

**Comment by azesmway** [comment] 2019-09-28 10:29
> Hi,
> This lib is working and it shows in app list when I try to share photos, images or documents.
> 
> But this lib does not work when I try to export chat from whtsapp, other apps like message, email etc are showing but my app which I build is not showing in the list.
> Please help I am trying to build a share extension for whatsapp
> 
> My package.json
> 
> "dependencies": {
> "react": "16.8.6",
> "react-native": "0.60.5",
> "react-native-file-share-intent": "^1.1.2"
> },

Hi
You can tell. I can’t even run where to find the correct installation instructions? I constantly have a mistake - I don’t see React

**Comment by sidpauhal** [comment] 2019-10-02 16:19
Hi
This library works on Android but not in IOS
also export from whatsapp is not working in android

Any help?

**Comment by azesmway** [comment] 2019-10-02 16:24
> Hi
> This library works on Android but not in IOS
> also export from whatsapp is not working in android
> 
> Any help?

Where can I find a working option for share for ios?

**Comment by ajith-ab** [comment] 2019-11-09 07:39
Duplicate of #10

**Comment by BalaRajendran** [comment] 2019-11-19 08:34
Is this Issue is fixed?

**Comment by BalaRajendran** [comment] 2019-11-26 01:56
> @ajith-ab Any update on this?

Did you finished?

**Comment by ajith-ab** [comment] 2020-05-31 18:21
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Closed by ajith-ab** 2020-05-31 18:21 UTC
