### ISSUE TITLE
Getting error with URL share (brave browser)

### ISSUE THREAD

**Issue by annraveendran** [ajith-ab/react-native-file-share-intent#14] opened 2019-10-31 07:25 UTC
Share is working in safari but getting error in brave.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'*** First throw call stack:

Could you please check.

**Comment by ajith-ab** [comment] 2019-11-09 07:41
Duplicate of #10

**Comment by ajith-ab** [comment] 2020-05-31 18:19
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Closed by ajith-ab** 2020-05-31 18:19 UTC
